#
#    This file is part of the Pi Entertainment System (PES).
#
#    PES provides an interactive GUI for games console emulators
#    and is designed to work on the Raspberry Pi.
#
#    Copyright (C) 2020 Neil Munday (neil@mundayweb.com)
#
#    PES is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PES is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with PES.  If not, see <http://www.gnu.org/licenses/>.
#

---

- name: "set hostname"
  hostname:
    name: pes

- name: "set timezone to Europe/London"
  timezone:
    name: Europe/London

- name: "set keyboard layout to UK"
  command: localectl set-keymap --no-convert uk

- name: "disable core files"
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: '^DumpCore='
    insertafter: '^#DumpCore='
    line: DumpCore=no

- name: "limit journal file to 50MB"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^SystemMaxUse='
    insertafter: '^#SystemMaxUse='
    line: SystemMaxUse=50M

- name: "disable DNSSEC - we don't have a RTC"
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSSEC='
    insertafter: '^#DNSSEC='
    line: DNSSEC=no

- name: "enable dhcpcd"
  service:
    name: dhcpcd
    state: started
    enabled: yes

- name: "add udev rules for USB control pads"
  copy:
    src: 99-evdev.rules
    dest: /etc/udev/rules.d/99-evdev.rules
    owner: root
    group: root
    mode: 0644

- name: "set-up root .bash_profile"
  copy:
    src: bash_profile
    dest: /root/.bash_profile
    owner: root
    group: root
    mode: 0600

- name: "set-up root .bashrc"
  copy:
    src: bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0600

- name: "set-up pi .bash_profile"
  copy:
    src: bash_profile
    dest: /home/pi/.bash_profile
    owner: pi
    group: pi
    mode: 0600

- name: "set-up pi .bashrc"
  copy:
    src: bashrc
    dest: /home/pi/.bashrc
    owner: pi
    group: pi
    mode: 0600

- name: "set-up makepkg.conf"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: '^MAKEFLAGS='
    insertafter: '^#MAKEFLAGS='
    line: MAKEFLAGS="-j {{ ansible_processor_vcpus }}"
